"""Migrations

Revision ID: 2f0c506f2550
Revises: 94ffbf1114c5
Create Date: 2025-04-27 21:33:16.387916

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f0c506f2550"
down_revision = "init"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "game_stats",
        sa.Column("is_won", sa.Boolean(), nullable=False),
        sa.Column("unsuccessfully_clicks", sa.INTEGER(), nullable=False),
        sa.Column("successfully_clicks", sa.INTEGER(), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_stats")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
